<?php
return [
    'Attention Seekers' => [
        'animate__bounce'     => 'Bounce',
        'animate__flash'      => 'Flash',
        'animate__pulse'      => 'Pulse',
        'animate__rubberBand' => 'Rubber Band',
        'animate__shakeX'     => 'Shake X',
        'animate__shakeY'     => 'Shake Y',
        'animate__headShake'  => 'Head Shake',
        'animate__swing'      => 'Swing',
        'animate__tada'       => 'Tada',
        'animate__wobble'     => 'Wobble',
        'animate__jello'      => 'Jello',
        'animate__heartBeat'  => 'Heart Beat',
    ],
    'Back Entrances' => [
        'animate__backInDown'  => 'Back In Down',
        'animate__backInLeft'  => 'Back In Left',
        'animate__backInRight' => 'Back In Right',
        'animate__backInUp'    => 'Back In Up',
    ],
    'Bouncing Entrances' => [
        'animate__bounceIn'      => 'Bounce In',
        'animate__bounceInDown'  => 'Bounce In Down',
        'animate__bounceInLeft'  => 'Bounce In Left',
        'animate__bounceInRight' => 'Bounce In Right',
        'animate__bounceInUp'    => 'Bounce In Up',
    ],
    'Fading Entrances' => [
        'animate__fadeIn'         => 'Fade In',
        'animate__fadeInDown'     => 'Fade In Down',
        'animate__fadeInDownBig'  => 'Fade In Down Big',
        'animate__fadeInLeft'     => 'Fade In Left',
        'animate__fadeInLeftBig'  => 'Fade In Left Big',
        'animate__fadeInRight'    => 'Fade In Right',
        'animate__fadeInRightBig' => 'Fade In Right Big',
        'animate__fadeInUp'       => 'Fade In Up',
        'animate__fadeInUpBig'    => 'Fade In Up Big',
    ],
    'Zoom Entrances' => [
        'animate__zoomIn'      => 'Zoom In',
        'animate__zoomInDown'  => 'Zoom In Down',
        'animate__zoomInLeft'  => 'Zoom In Left',
        'animate__zoomInRight' => 'Zoom In Right',
        'animate__zoomInUp'    => 'Zoom In Up',
    ],
    'Slide Entrances' => [
        'animate__slideInDown'  => 'Slide In Down',
        'animate__slideInLeft'  => 'Slide In Left',
        'animate__slideInRight' => 'Slide In Right',
        'animate__slideInUp'    => 'Slide In Up',
    ],
];
