<?php
return [
    'Attention Seekers' => [
        'ball'      => 'Ball',
        'blink'     => 'Blink',
        'shake'     => 'Shake',
        'pulsate'   => 'Pulsate',
        'spin'      => 'Spin',
    ],
    'Fading Entrances' => [
        'fadeIn'        => 'Fade In',
        'fadeInTop'     => 'Fade In Top',
        'fadeInBottom'  => 'Fade In Bottom',
        'fadeInLeft'    => 'Fade In Left',
        'fadeInRight'   => 'Fade In Right',
    ],
    'Fading Exits' => [
        'fadeOut'        => 'Fade Out',
        'fadeOutTop'     => 'Fade Out Top',
        'fadeOutBottom'  => 'Fade Out Bottom',
        'fadeOutLeft'    => 'Fade Out Left',
        'fadeOutRight'   => 'Fade Out Right',
    ],
    'Drive Entrances' => [
        'driveInTop'     => 'Drive In Top',
        'driveInBottom'  => 'Drive In Bottom',
        'driveInLeft'    => 'Drive In Left',
        'driveInRight'   => 'Drive In Right',
    ],
    'Drive Exits' => [
        'driveOutTop'     => 'Drive Out Top',
        'driveOutBottom'  => 'Drive Out Bottom',
        'driveOutLeft'    => 'Drive Out Left',
        'driveOutRight'   => 'Drive Out Right',
    ],
    'Jump Animations' => [
        'jumpInLeft'     => 'Jump In Left',
        'jumpInRight'    => 'Jump In Right',
        'jumpOutLeft'    => 'Jump Out Left',
        'jumpOutRight'   => 'Jump Out Right',
    ],
    'Roll Animations' => [
        'rollInTop'      => 'Roll In Top',
        'rollInBottom'   => 'Roll In Bottom',
        'rollInLeft'     => 'Roll In Left',
        'rollInRight'    => 'Roll In Right',
        'rollOutTop'     => 'Roll Out Top',
        'rollOutBottom'  => 'Roll Out Bottom',
        'rollOutLeft'    => 'Roll Out Left',
        'rollOutRight'   => 'Roll Out Right',
    ],
    'Pop Animations' => [
        'popIn'          => 'Pop In',
        'popInTop'       => 'Pop In Top',
        'popInBottom'    => 'Pop In Bottom',
        'popInLeft'      => 'Pop In Left',
        'popInRight'     => 'Pop In Right',
        'popOut'         => 'Pop Out',
        'popOutTop'      => 'Pop Out Top',
        'popOutBottom'   => 'Pop Out Bottom',
        'popOutLeft'     => 'Pop Out Left',
        'popOutRight'    => 'Pop Out Right',
    ],
    'Pull Animations' => [
        'pullUp'     => 'Pull Up',
        'pullDown'   => 'Pull Down',
        'pullLeft'   => 'Pull Left',
        'pullRight'  => 'Pull Right',
    ],
    'Swoop Animations' => [
        'swoopInTop'     => 'Swoop In Top',
        'swoopInBottom'  => 'Swoop In Bottom',
        'swoopInLeft'    => 'Swoop In Left',
        'swoopInRight'   => 'Swoop In Right',
        'swoopOutTop'    => 'Swoop Out Top',
        'swoopOutBottom' => 'Swoop Out Bottom',
        'swoopOutLeft'   => 'Swoop Out Left',
        'swoopOutRight'  => 'Swoop Out Right',
    ],
    'Flip & Fold' => [
        'flip'        => 'Flip',
        'flipInX'     => 'Flip In X',
        'flipInY'     => 'Flip In Y',
        'flipOutX'    => 'Flip Out X',
        'flipOutY'    => 'Flip Out Y',
        'fold'        => 'Fold',
        'unfold'      => 'Unfold',
    ],
    'Hit Animations' => [
        'hitLeft'   => 'Hit Left',
        'hitRight'  => 'Hit Right',
    ],
];
